<?php

namespace App\Form;

use App\Entity\Product;
use App\Entity\QRTag;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType; // Import TextType
use Symfony\Component\Form\Extension\Core\Type\ChoiceType; // Keep if you actually need it for a dropdown of existing paths
use Symfony\Component\OptionsResolver\OptionsResolver;

class QRTagType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            // Field to select the Product
            ->add('product', EntityType::class, [
                'class' => Product::class,
                'choice_label' => 'name', // Display product name in the dropdown
                'placeholder' => 'Select a product',
                'required' => true, // A product must be selected to generate a QR
                'label' => 'Link to Product',
            ])
            // Field to display the generated QR Code URL (read-only)
            ->add('qrCodeValue', TextType::class, [ // Explicitly use TextType
                'label' => 'Generated QR Code URL',
                'required' => false, // It's generated, not user input
                'attr' => [
                    'readonly' => true, // Make it read-only
                    'placeholder' => 'Automatically generated after selecting a product and saving', // Placeholder text
                ],
                // On 'edit', you want to show the existing value
                // On 'new', it will be empty until saved
            ])
            // If dateGenerated is set automatically, remove it from the form
            // Or make it hidden/readonly if you want to display it
            ->add('dateGenerated', null, [
                'label' => 'Date Generated',
                'widget' => 'single_text', // For date types
                'disabled' => true, // User cannot change it
                'required' => false,
                'view_timezone' => 'Asia/Manila',
            ]);

        // Remove qrImagePath from the form if it's always generated by the controller
        // If you still want to display it for informational purposes, make it read-only TextType
        // For 'new' form, the image path doesn't exist yet, so it won't be a choice.
        // If you are editing, you might display it as read-only.
        $builder->add('qrImagePath', TextType::class, [
            'label' => 'QR Image File Name',
            'required' => false,
            'attr' => [
                'readonly' => true, // Make it read-only
                'placeholder' => 'Generated after saving',
            ],
        ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => QRTag::class,
            // 'qr_image_paths' => [], // Removed as it's no longer used for ChoiceType dropdown
        ]);
    }
}
